# Generated by Django 3.1.3 on 2021-01-12 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, verbose_name='Gender')),
                ('bio', models.TextField(blank=True, max_length=250, null=True, verbose_name='Bio')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=15, verbose_name='Country')),
                ('address_details', models.CharField(max_length=15, verbose_name='Detailed address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Profile Picture')),
                ('joined', models.DateTimeField(auto_now_add=True, verbose_name='Joined')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
