# Generated by Django 3.1.3 on 2020-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201219_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=15, verbose_name='المدينة؟'),
            preserve_default=False,
        ),
    ]
