# Generated by Django 3.1.3 on 2020-12-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201220_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_detail',
            new_name='address_details',
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(default='إستشارى', max_length=30, verbose_name='الدرجة العلمية'),
        ),
    ]
