# Generated by Django 3.1.3 on 2020-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201220_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(default='باطنة', max_length=30, verbose_name='دكتور؟'),
        ),
    ]
